#!/usr/bin/env python3
"""Generate every results table and every inline result macro from the CSVs in
figures/data/.

Nothing in the manuscript body types an experimental number by hand: the body
either \\input's a file from tables/ or calls a macro from macros/results.tex.
Re-running this script after a change to the experiments updates both.

Usage:  python3 scripts/make_tables.py
"""
from __future__ import annotations

import re
import os
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "figures" / "data"
def paper_root() -> Path:
    """Where the manuscript lives.

    The paper repository carries only what a compile needs -- sources, class
    files, the figure PDFs -- so this toolchain lives in the code repository
    beside the raw results and writes its products across. Override with
    $HCMAGRL_PAPER; the default is the sibling checkout.
    """
    return Path(os.environ.get(
        "HCMAGRL_PAPER",
        Path(__file__).resolve().parents[3] / "Junxin_Huang_HCMAGRL_RMS_FRT"))


PAPER = paper_root()
TABLES = PAPER / "tables"
MACROS = PAPER / "macros"

OURS = "HCMAGRL"
ABLATION = ["w/o EdgeAttn", "w/o Hierarchy", "w/o Heterogeneity", "w/o Graph"]
RL = ["DDQN", "EDQN", "SAC", "D-DRL"]
ORDER = [OURS] + ABLATION + RL

# Method label -> LaTeX label used in the tables.
TEX = {
    OURS: r"\textbf{HCMAGRL}",
    "w/o EdgeAttn": r"HCMAGRL$-$A",
    "w/o Hierarchy": r"HCMAGRL$-$H",
    "w/o Heterogeneity": r"HCMAGRL$-$T",
    "w/o Graph": r"HCMAGRL$-$G",
    "DDQN": "DDQN", "EDQN": "EDQN", "SAC": "SAC", "D-DRL": "D-DRL",
}
# Macro-safe names (LaTeX control sequences may only contain letters).
SLUG = {
    OURS: "Ours", "w/o EdgeAttn": "NoAttn", "w/o Hierarchy": "NoHier",
    "w/o Heterogeneity": "NoHet", "w/o Graph": "NoGraph",
    "DDQN": "DDQN", "EDQN": "EDQN", "SAC": "SAC", "D-DRL": "DDRL",
}

HEADER = ("%% Generated by scripts/make_tables.py -- do not edit by hand.\n"
          "%% Regenerate with: python3 scripts/make_tables.py\n")

macros: dict[str, str] = {}


def put(name: str, value: str) -> None:
    macros[name] = value


def stars(p: float) -> str:
    return "$^{***}$" if p < 1e-3 else "$^{**}$" if p < 1e-2 else "$^{*}$" if p < 0.05 else ""


def fmt_p(p: float) -> str:
    return r"$<$0.001" if p < 1e-3 else f"{p:.3f}"


def write(path: Path, body: str) -> None:
    path.write_text(HEADER + body)
    print(f"  {path.relative_to(PAPER)}")


# --------------------------------------------------------------------------
def table_instances(inst: pd.DataFrame) -> None:
    rows = []
    for _, r in inst.iterrows():
        name = r.instance_id.replace("_", "\\_")
        rows.append(
            f"{r.cid} & {name} & {r.M} & {r.A} & {r.R} & "
            f"{r.J} & {r.op_types} & {r.n_jobs} & {r.n_operations} & "
            f"{r.avg_elig_machines:.2f} & {r.avg_elig_modules:.2f} & "
            f"{r.avg_reconfig_time:.1f} & {r.avg_fuzzy_spread:.1f} & "
            f"{r.avg_reconfig_cost:.1f} \\\\")
    body = (r"""\begin{tabular}{llrrrrrrrrrrrr}
\toprule
 &  & \multicolumn{4}{c}{Dimensions} & \multicolumn{3}{c}{Workload} &
 \multicolumn{2}{c}{Flexibility} & \multicolumn{3}{c}{Reconfiguration} \\
\cmidrule(lr){3-6}\cmidrule(lr){7-9}\cmidrule(lr){10-11}\cmidrule(lr){12-14}
ID & Instance & $M$ & $A$ & $R$ & $J$ & $|\mathcal{O}|$ & jobs & ops &
 cells & mod. & $\bar{t}$ & $\overline{u-\ell}$ & $\bar{c}$ \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}""")
    write(TABLES / "instances.tex", body)
    put("NumInstances", str(len(inst)))
    put("MinOps", str(int(inst.n_operations.min())))
    put("MaxOps", str(int(inst.n_operations.max())))
    put("MinJobs", str(int(inst.n_jobs.min())))
    put("MaxJobs", str(int(inst.n_jobs.max())))
    put("MeanFuzzySpread", f"{inst.avg_fuzzy_spread.mean():.1f}")
    put("MeanReconfigTime", f"{inst.avg_reconfig_time.mean():.1f}")


# --------------------------------------------------------------------------
def table_main(cells: pd.DataFrame, pair: pd.DataFrame) -> None:
    cells = cells.copy()
    cells["M"] = cells.instance_id.str.extract(r"M(\d+)_").astype(int)
    out = []
    for m in ORDER:
        d = cells[cells.method == m]
        cs = []
        for M in (4, 8, 12):
            g = d[d.M == M]
            cs += [f"{g.makespan_mean.mean():.1f}", f"{g.cost_mean.mean():.1f}"]
        cs += [f"{d.makespan_mean.mean():.1f}", f"{d.cost_mean.mean():.1f}"]
        out.append((m, cs))

    # Bold the best value in each column.
    best = []
    for c in range(8):
        vals = [float(cs[c]) for _, cs in out]
        best.append(min(vals))
    rows = []
    for m, cs in out:
        cells_tex = []
        for c, v in enumerate(cs):
            cells_tex.append(rf"\textbf{{{v}}}" if float(v) == best[c] else v)
        rows.append(f"{TEX[m]} & " + " & ".join(cells_tex) + r" \\")
    rows.insert(1, r"\addlinespace")
    rows.insert(6, r"\addlinespace")

    body = (r"""\begin{tabular}{lrrrrrrrr}
\toprule
 & \multicolumn{2}{c}{$M=4$} & \multicolumn{2}{c}{$M=8$} &
 \multicolumn{2}{c}{$M=12$} & \multicolumn{2}{c}{All instances} \\
\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}\cmidrule(lr){8-9}
Method & $C_{\max}$ & $Z$ & $C_{\max}$ & $Z$ & $C_{\max}$ & $Z$ & $C_{\max}$ & $Z$ \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}""")
    write(TABLES / "main_results.tex", body)

    for m in ORDER:
        d = cells[cells.method == m]
        put(f"Makespan{SLUG[m]}", f"{d.makespan_mean.mean():.1f}")
        put(f"Cost{SLUG[m]}", f"{d.cost_mean.mean():.1f}")


# --------------------------------------------------------------------------
def table_stats(pair: pd.DataFrame, summ: pd.DataFrame) -> None:
    rows = []
    for group, members in (("Ablated variants", ABLATION),
                           ("Reinforcement learning baselines", RL)):
        rows.append(rf"\multicolumn{{8}}{{l}}{{\textit{{{group}}}}} \\")
        for m in members:
            r = pair[(pair.metric == "score") & (pair.method_b == m)].iloc[0]
            rm = pair[(pair.metric == "makespan") & (pair.method_b == m)].iloc[0]
            rc = pair[(pair.metric == "cost") & (pair.method_b == m)].iloc[0]
            rows.append(
                f"\\quad {TEX[m]} & {rm.rel_gap_pct:+.2f} & {fmt_p(rm.p_value)}{stars(rm.p_value)} & "
                f"{rc.rel_gap_pct:+.2f} & {fmt_p(rc.p_value)}{stars(rc.p_value)} & "
                f"{r.rel_gap_pct:+.2f} & {fmt_p(r.p_value)}{stars(r.p_value)} & "
                f"{r.cohens_d:+.2f} \\\\")
        rows.append(r"\addlinespace")
    n = int(pair[pair.metric == "score"].n_pairs.iloc[0])
    body = (r"""\begin{tabular}{lrrrrrrr}
\toprule
 & \multicolumn{2}{c}{Makespan $C_{\max}$} & \multicolumn{2}{c}{Cost $Z$} &
 \multicolumn{3}{c}{Scalarized score} \\
\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-8}
HCMAGRL versus & $\Delta$ (\%) & $p$ & $\Delta$ (\%) & $p$ & $\Delta$ (\%) & $p$ &
 Cohen's $d$ \\
\midrule
""" + "\n".join(rows[:-1]) + r"""
\bottomrule
\multicolumn{8}{l}{\footnotesize Paired Wilcoxon signed-rank test over
 $N=""" + str(n) + r"""$ (instance, weight) settings; each is a mean over 20} \\
\multicolumn{8}{l}{\footnotesize evaluation seeds. Negative $\Delta$ favours
 HCMAGRL. $^{*}p<0.05$, $^{**}p<0.01$, $^{***}p<0.001$.} \\
\end{tabular}""")
    write(TABLES / "statistics.tex", body)

    for _, r in pair.iterrows():
        tag = {"score": "Score", "makespan": "Ms", "cost": "Cost"}[r.metric]
        put(f"Gap{tag}{SLUG[r.method_b]}", f"{abs(r.rel_gap_pct):.1f}\\%")
        put(f"P{tag}{SLUG[r.method_b]}",
            "$<$0.001" if r.p_value < 1e-3 else f"{r.p_value:.3f}")
    put("NCells", str(n))
    # Per-family Friedman/Nemenyi macros: FriedmanChiAblation, NemenyiCDAblation,
    # RankAblationOurs, ... plus the pooled nine-method family "All".
    for fam in summ["family"].unique():
        f = summ[summ.family == fam]
        tag = fam.capitalize()
        put(f"FriedmanChi{tag}", f"{f.friedman_chi2.iloc[0]:.1f}")
        put(f"NemenyiCD{tag}", f"{f.nemenyi_cd.iloc[0]:.3f}")
        put(f"KMethods{tag}", str(int(f.k_methods.iloc[0])))
        for _, r in f.iterrows():
            put(f"Rank{tag}{SLUG[r.method]}", f"{r.avg_rank:.2f}")
            if r.method != OURS:
                put(f"RankGap{tag}{SLUG[r.method]}", f"{r.gap_to_best:.2f}")
        sep = f[(f.method != OURS) & f.separated]["method"].tolist()
        put(f"NSeparated{tag}", str(len(sep)))


# --------------------------------------------------------------------------
def table_ranks(summ: pd.DataFrame) -> None:
    """Average ranks with the Nemenyi outcome, per comparison family."""
    rows = []
    for fam, label in (("baseline", "Reinforcement learning baselines"),
                       ("ablation", "Ablated variants")):
        f = summ[summ.family == fam].sort_values("avg_rank")
        cd = f.nemenyi_cd.iloc[0]
        chi2 = f.friedman_chi2.iloc[0]
        p = f.friedman_p.iloc[0]
        rows.append(rf"\multicolumn{{4}}{{l}}{{\textit{{{label}}}: "
                    rf"$\chi^2={chi2:.1f}$, $p={fmt_p(p).replace('$<$', '<')}$, "
                    rf"CD $={cd:.3f}$}} \\")
        for _, r in f.iterrows():
            if r.method == OURS:
                rows.append(rf"\quad {TEX[r.method]} & \textbf{{{r.avg_rank:.2f}}} "
                            r"& --- & --- \\")
            else:
                mark = r"\checkmark" if r.separated else r"$\circ$"
                rows.append(f"\\quad {TEX[r.method]} & {r.avg_rank:.2f} & "
                            f"{r.gap_to_best:+.2f} & {mark} \\\\")
        rows.append(r"\addlinespace")
    body = (r"""\begin{tabular}{lrrc}
\toprule
Method & Avg. rank & $\Delta$ rank & Separated \\
\midrule
""" + "\n".join(rows[:-1]) + r"""
\bottomrule
\multicolumn{4}{l}{\footnotesize Friedman test with the Nemenyi post-hoc
 procedure over $N=135$ blocks, computed} \\
\multicolumn{4}{l}{\footnotesize separately within each family. Lower ranks are
 better. \checkmark: the gap to} \\
\multicolumn{4}{l}{\footnotesize HCMAGRL exceeds the critical difference;
 $\circ$: it does not.} \\
\end{tabular}""")
    write(TABLES / "ranks.tex", body)


def table_indicators(ind: pd.DataFrame, win: pd.DataFrame) -> None:
    for group, members in (("rl", [OURS] + RL), ("ablation", [OURS] + ABLATION)):
        rows = []
        for ind_name in ("IGD", "Spread", "HV"):
            sub = ind[(ind.group == group) & (ind.indicator == ind_name)]
            means = {m: sub[sub.method == m]["value"].mean() for m in members}
            wins = {m: win[(win.group == group) & (win.indicator == ind_name)
                           & (win.method == m)]["win_rate"].iloc[0] for m in members}
            target = max if ind_name == "HV" else min
            bestv = target(means.values())
            cs = []
            for m in members:
                v = f"{means[m]:.3f}"
                cs.append(rf"\textbf{{{v}}}" if means[m] == bestv else v)
            rows.append(f"{ind_name} (mean) & " + " & ".join(cs) + r" \\")
            bw = max(wins.values())
            cs = []
            for m in members:
                v = f"{wins[m]:.1f}"
                cs.append(rf"\textbf{{{v}}}" if wins[m] == bw else v)
            rows.append(r"\quad win rate (\%) & " + " & ".join(cs) + r" \\")
            rows.append(r"\addlinespace")
            for m in members:
                put(f"{ind_name}Win{SLUG[m]}{group.capitalize()}", f"{wins[m]:.1f}\\%")
        head = " & ".join(TEX[m] for m in members)
        body = (r"\begin{tabular}{l" + "r" * len(members) + r"""}
\toprule
Indicator & """ + head + r""" \\
\midrule
""" + "\n".join(rows[:-1]) + r"""
\bottomrule
\multicolumn{""" + str(len(members) + 1) + r"""}{l}{\footnotesize Means over the
 27 instances. IGD and Spread are minimized, HV is maximized.} \\
\end{tabular}""")
        write(TABLES / f"indicators_{group}.tex", body)


# --------------------------------------------------------------------------
def table_benchmark(bm: pd.DataFrame) -> None:
    """Instance sizes are the rows: with 12 sizes and 5 algorithms under two
    budgets, the transposed layout is the only one that fits the text width."""
    sizes = bm[bm.criterion == "evaluations"]["size"].unique().tolist()
    algos = ["SADE", "MSELS", "IGA", "DABC", OURS]
    crits = ("evaluations", "runtime")
    tab = {(c, a): bm[(bm.criterion == c) & (bm.algorithm == a)]
                     .set_index("size")["makespan"] for c in crits for a in algos}

    rows = []
    for s in sizes + ["Average"]:
        cells = []
        for c in crits:
            vals = {a: (tab[(c, a)].reindex(sizes).mean() if s == "Average"
                        else tab[(c, a)].get(s, np.nan)) for a in algos}
            best = min(vals.values())
            for a in algos:
                t = f"{vals[a]:.1f}"
                cells.append(rf"\textbf{{{t}}}" if vals[a] == best else t)
        label = s if s == "Average" else s.replace("x", r"$\times$")
        if s == "Average":
            rows.append(r"\midrule")
            label = r"\textit{Average}"
        rows.append(f"{label} & " + " & ".join(cells) + r" \\")

    head = " & ".join(TEX.get(a, a) for a in algos)
    body = (r"\begin{tabular}{l" + "r" * (2 * len(algos)) + r"""}
\toprule
 & \multicolumn{5}{c}{Termination: $m\,n\times 1000$ evaluations}
 & \multicolumn{5}{c}{Termination: $m\,n\times 8$\,s} \\
\cmidrule(lr){2-6}\cmidrule(lr){7-11}
Size $m\times n$ & """ + head + " & " + head + r""" \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\multicolumn{11}{l}{\footnotesize Makespan on the public RMSSP benchmark. The
 metaheuristic results are reported under the two termination criteria used by} \\
\multicolumn{11}{l}{\footnotesize their source; HCMAGRL is a single set of
 results compared against both. Best value per block in bold.} \\
\end{tabular}""")
    write(TABLES / "benchmark.tex", body)

    ours = bm[(bm.criterion == "evaluations") & (bm.algorithm == OURS)]["makespan"].mean()
    for a in ("DABC", "IGA", "SADE", "MSELS"):
        for crit, tag in (("evaluations", "Ev"), ("runtime", "Rt")):
            v = bm[(bm.criterion == crit) & (bm.algorithm == a)]["makespan"].mean()
            put(f"Bench{tag}{a}", f"{v:.1f}")
            # Reported as a magnitude; the direction is stated in words.
            put(f"BenchGap{tag}{a}", f"{abs(100 * (ours - v) / v):.1f}\\%")
    put("BenchOurs", f"{ours:.1f}")


# --------------------------------------------------------------------------
def table_runtime(rt: pd.DataFrame) -> None:
    rows = []
    for m in ORDER:
        d = rt[rt.method == m]
        if d.empty:
            continue
        cs = [f"{d[d.M == M].sec_per_episode.mean():.2f}" for M in (4, 8, 12)]
        rows.append(f"{TEX[m]} & " + " & ".join(cs) +
                    f" & {d.sec_per_episode.mean():.2f} \\\\")
    body = (r"""\begin{tabular}{lrrrr}
\toprule
Method & $M=4$ & $M=8$ & $M=12$ & Mean \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\multicolumn{5}{l}{\footnotesize Wall-clock seconds per training episode,
 averaged over the nine instances} \\
\multicolumn{5}{l}{\footnotesize of each size group at $\alpha_t=\alpha_c=0.5$.} \\
\end{tabular}""")
    write(TABLES / "runtime.tex", body)
    for m in ORDER:
        d = rt[rt.method == m]
        if not d.empty:
            put(f"Sec{SLUG[m]}", f"{d.sec_per_episode.mean():.2f}")


# --------------------------------------------------------------------------
# Dominance counts behind the two front figures
# --------------------------------------------------------------------------
PARETO_RL_CIDS = ["C11", "C18", "C21", "C23", "C24", "C25"]
PARETO_ABL_CIDS = ["C3", "C5", "C17", "C19", "C20", "C21"]


def pareto_macros(pts: pd.DataFrame) -> None:
    """How the plotted fronts stand against ours, counted rather than eyeballed."""
    f = pts[pts.nondominated]

    def dominated(a, b):
        """Rows of b that some row of a dominates."""
        return sum(bool(np.any(np.all(a <= p, axis=1) & np.any(a < p, axis=1)))
                   for p in b)

    for tag, rivals, cids in (("Rl", RL, PARETO_RL_CIDS),
                              ("Abl", ABLATION, PARETO_ABL_CIDS)):
        beaten = total = lost = mine = 0
        for c in cids:
            ours = f[(f.cid == c) & (f.method == OURS)][["makespan", "cost"]].to_numpy()
            them = f[(f.cid == c) & (f.method.isin(rivals))][["makespan", "cost"]].to_numpy()
            total += len(them)
            mine += len(ours)
            beaten += dominated(ours, them)
            lost += dominated(them, ours)
        put(f"FrontBeaten{tag}", str(beaten))
        put(f"FrontTotal{tag}", str(total))
        put(f"FrontLost{tag}", str(lost))
        put(f"FrontOurs{tag}", str(mine))


# --------------------------------------------------------------------------
def main() -> None:
    TABLES.mkdir(exist_ok=True)
    MACROS.mkdir(exist_ok=True)
    print("tables:")
    inst = pd.read_csv(DATA / "instances.csv")
    cells = pd.read_csv(DATA / "eval_cells.csv")
    pair = pd.read_csv(DATA / "stats_pairwise.csv")
    summ = pd.read_csv(DATA / "stats_summary.csv")
    ind = pd.read_csv(DATA / "indicators.csv")
    win = pd.read_csv(DATA / "indicator_winrate.csv")
    bm = pd.read_csv(DATA / "benchmark_rmssp.csv")
    rt = pd.read_csv(DATA / "runtime.csv")
    pts = pd.read_csv(DATA / "pareto_points.csv")

    table_instances(inst)
    table_main(cells, pair)
    table_stats(pair, summ)
    table_ranks(summ)
    table_indicators(ind, win)
    table_benchmark(bm)
    table_runtime(rt)
    pareto_macros(pts)

    lines = [HEADER]
    for name in sorted(macros):
        assert re.fullmatch(r"[A-Za-z]+", name), name
        lines.append(f"\\newcommand{{\\{name}}}{{{macros[name]}\\xspace}}")
    (MACROS / "results.tex").write_text("\n".join(lines) + "\n")
    print(f"\nmacros: {len(macros)} definitions -> macros/results.tex")


if __name__ == "__main__":
    main()
